//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monopoli.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monopoli.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Botte {
            get {
                object obj = ResourceManager.GetObject("Botte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cactus {
            get {
                object obj = ResourceManager.GetObject("Cactus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Candela {
            get {
                object obj = ResourceManager.GetObject("Candela", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot; ?&gt;
        ///&lt;Monopoli&gt;
        ///  &lt;MaxPlayers&gt;6&lt;/MaxPlayers&gt;
        ///  &lt;MinPlayers&gt;2&lt;/MinPlayers&gt;
        ///  &lt;CurrencySymbol&gt;&amp;#x20AC;&lt;/CurrencySymbol&gt;
        ///  &lt;InitialMoney&gt;
        ///    &lt;Money playersNum=&quot;2&quot;&gt;8750&lt;/Money&gt;
        ///    &lt;Money playersNum=&quot;3&quot;&gt;7500&lt;/Money&gt;
        ///    &lt;Money playersNum=&quot;4&quot;&gt;6250&lt;/Money&gt;
        ///    &lt;Money playersNum=&quot;5&quot;&gt;5000&lt;/Money&gt;
        ///    &lt;Money playersNum=&quot;6&quot;&gt;3750&lt;/Money&gt;
        ///  &lt;/InitialMoney&gt;
        ///  &lt;InitialDeeds&gt;
        ///    &lt;DeedNum playersNum=&quot;2&quot;&gt;7&lt;/DeedNum&gt;
        ///    &lt;DeedNum playersNum=&quot;3&quot;&gt;6&lt;/DeedNum&gt;
        ///    &lt;DeedNum [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Funghetto {
            get {
                object obj = ResourceManager.GetObject("Funghetto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imprevisti {
            get {
                object obj = ResourceManager.GetObject("imprevisti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap inPrigione {
            get {
                object obj = ResourceManager.GetObject("inPrigione", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon monopoli_icon_high {
            get {
                object obj = ResourceManager.GetObject("monopoli_icon_high", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap monopoli_logo {
            get {
                object obj = ResourceManager.GetObject("monopoli_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon monopoly_upperIcon {
            get {
                object obj = ResourceManager.GetObject("monopoly_upperIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Palla {
            get {
                object obj = ResourceManager.GetObject("Palla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap parcheggio {
            get {
                object obj = ResourceManager.GetObject("parcheggio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pera {
            get {
                object obj = ResourceManager.GetObject("Pera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap prigione {
            get {
                object obj = ResourceManager.GetObject("prigione", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap probabilità {
            get {
                object obj = ResourceManager.GetObject("probabilità", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Regolamento {
            get {
                object obj = ResourceManager.GetObject("Regolamento", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap societàAcquaPotabile {
            get {
                object obj = ResourceManager.GetObject("societàAcquaPotabile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap societàElettrica {
            get {
                object obj = ResourceManager.GetObject("societàElettrica", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stazione {
            get {
                object obj = ResourceManager.GetObject("stazione", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tassaDiLusso {
            get {
                object obj = ResourceManager.GetObject("tassaDiLusso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tassaPatrimoniale {
            get {
                object obj = ResourceManager.GetObject("tassaPatrimoniale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap via {
            get {
                object obj = ResourceManager.GetObject("via", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
